const email = 'test@email.com';
const username = 'newuser';
const password = 'password';
const url = 'https://leetcode.com/problems/two-sum/description/';
const urlname = 'Two Sum';
const disclaimer = '*Suggestions generated by an AI, some information maybe inaccurate.';
const geminiLabel = 'Get suggestions based on the list using Gemini';
const createList = "Create new List";

describe('New user journey', () => {
    it('should create user', () => {
        cy.visit('/signup');
        cy.url().should('include', '/signup');
        cy.contains('Sign Up');

        // Signup
        cy.get('#username').type(username);
        cy.get('#email').type(email);
        cy.get('#password').type(password);
        cy.get('#confirmPassword').type(password);
        cy.get('button').contains('Sign Up').click();

        // Signin
        // if (cy.contains('User already exists')) {
        //     cy.visit('/signin');
        //     cy.get('#email').type(email);
        //     cy.get('#password').type(password);
        //     cy.get('button').contains('Sign In').click();
        // }

        // Create new List
        cy.get(`button[title="${createList}"]`).click();
        cy.get('h6').contains(createList);
        cy.get('#list-name').type('New List');
        cy.get('button').contains('Create').click();

        // Add Question
        const addBtn = cy.contains('Add Question');
        cy.get('#url').type(url);
        cy.get('#name').type(urlname);
        cy.get('#difficulty').select('Easy');
        cy.get('#status').select('Done');
        cy.get('#category').select('Array');
        addBtn.click();
        cy.contains(urlname);

        // Check Suggestions
        cy.get('button').contains(geminiLabel).click();
        cy.contains(disclaimer, { timeout: 10000 });

        // Delete the list
        cy.get('button[title="Delete List"]').click();
        cy.get('button').contains(/^Delete$/).click();

        // Delete the account
        cy.get('a').contains('Profile').click();
        cy.get('button').contains('Delete account').click();
        cy.get('button').contains(/^Delete$/).click();
        cy.url().should('include', '/public-lists');
    })
})